### ISSUE TITLE
Limbo issue fix

### ISSUE THREAD

**Issue by quickdesh** [PixelMelt/Fragrun-Bot#1]
So I have been using your fragbot code (Thank you btw for making it) for a while and I made my own fix for the limbo problem, ill just post it here , hopefully it helps

```js

bot.addChatPatternSet('YOU_ARE_AFK',[/You are AFK. Move around to return from AFK./],{
			parse: true,
		})
		bot.on('chat:YOU_ARE_AFK',() => {
			console.log("LIMBO")
			bot.chat(`/lobby main`)
			waity(0.2)
			bot.chat(`/home`)
		})
```

**Comment by PixelMelt** [comment]
has the current fix not been working for you?

**Comment by quickdesh** [comment]
I actually have been using your code before you implemented a fix, so I had made my own.


 I just posted it here since I saw yours needed it to type "fix" to bring it out of limbo. Speaking of which, what happens if the people who are whitelisted but not in guild need to fix it? Maybe make it a pm?

**Comment by quickdesh** [comment]
Just went through your updated code, you did it already with scoreboard check as well which Is much better than mine. 

I just posted mine without seeing the code hoping it would help.

Sorry for the inconvenience I caused

Welp all is well that end well.

Thanks again for creating the og code!

**Comment by PixelMelt** [comment]
Ah, np dude I'm happy you're getting some use out of it.
